CREATE TABLE ISSUES (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
  repository_id         BIGINT NOT NULL,
  issue_type_id         BIGINT NOT NULL,
  analysis_request_id   BIGINT NOT NULL,
  insight_storage_id    BIGINT,
  order_id              BIGINT UNSIGNED,
  last_modified         datetime NOT NULL,
  issue_name            nvarchar(255) NOT NULL,
  issue_desc            text NOT NULL,
  severity              nvarchar(255) NOT NULL
);

CREATE TABLE ISSUE_TYPE (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  description     nvarchar(255) NOT NULL
);

CREATE TABLE ORDER_INFORMATION (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  start_date        datetime NOT NULL,
  due_date          datetime NOT NULL,
  issues_fix_cycle  datetime NOT NULL,
  status            nvarchar(255),
  fail_reason       nvarchar(255)
);

CREATE TABLE ANALYSIS_REQUEST (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  repository_id     BIGINT NOT NULL,
  request_id        nvarchar(255),
  batch_id          varchar(255),
  revision          nvarchar(255),
  status            nvarchar(255),
  last_updated      datetime NOT NULL
);
