CREATE TABLE FIXES
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    issue_id        BIGINT not null,
    customer_id     BIGINT not null,
    df_jira_key     nvarchar(255),
    pr_merged_time  timestamp,
    FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id),
    FOREIGN KEY (issue_id) REFERENCES ISSUES(id)
);
