CREATE TABLE ISSUE_PRIORITY (
  issue_id        BIGINT UNSIGNED NOT NULL PRIMARY KEY ,
  priority        BIGINT UNSIGNED
);

ALTER TABLE `ISSUE_PRIORITY`
ADD CONSTRAINT `FK_ISSUE`
  FOREIGN KEY (`issue_id`)
  REFERENCES `issues` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
