SET foreign_key_checks=0;

ALTER TABLE `REPOSITORIES` CHANGE COLUMN `customer_id` `customer_id` BIGINT(20) UNSIGNED NOT NULL;

ALTER TABLE `REPOSITORIES`
ADD CONSTRAINT `FK_REPO_CUSTOMER`
  FOREIGN KEY (`customer_id`)
  REFERENCES `customers` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `ORDER_INFORMATION` CHANGE COLUMN `customer_id` `customer_id` BIGINT(20) UNSIGNED NOT NULL;

ALTER TABLE `ORDER_INFORMATION`
ADD CONSTRAINT `FK_ORDERINFO_CUSTOMER`
  FOREIGN KEY (`customer_id`)
  REFERENCES `customers` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `FIXES` DROP FOREIGN KEY `fixes_ibfk_2`;
ALTER TABLE `FIXES` DROP COLUMN `customer_id`;

SET foreign_key_checks=1;
